language: python
sudo: false
os:
  - linux

python:
  - "3.9"
  - "3.10"

install:
  - pip install -r requirements.txt

script:
  - pytest

notifications:
  email:
    receipents: mushfiqur@anchorblock.vc
    on_success: never
    on_failure: always
    on_start: never
