language: python
sudo: false
os:
  - linux

python:
  - "3.9"
  - "3.10"

script:
  - "pytest test*"

notifications:
  email:
    receipents: u1604123@student.cuet.ac.bd
    on_success: never
    on_failure: always
    on_start: never
